// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_db_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_db_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_db_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_db_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_db_2eproto;
namespace Proto {
class LastWorld;
struct LastWorldDefaultTypeInternal;
extern LastWorldDefaultTypeInternal _LastWorld_default_instance_;
class Player;
struct PlayerDefaultTypeInternal;
extern PlayerDefaultTypeInternal _Player_default_instance_;
class PlayerBase;
struct PlayerBaseDefaultTypeInternal;
extern PlayerBaseDefaultTypeInternal _PlayerBase_default_instance_;
class PlayerMisc;
struct PlayerMiscDefaultTypeInternal;
extern PlayerMiscDefaultTypeInternal _PlayerMisc_default_instance_;
class Vector3;
struct Vector3DefaultTypeInternal;
extern Vector3DefaultTypeInternal _Vector3_default_instance_;
}  // namespace Proto
PROTOBUF_NAMESPACE_OPEN
template<> ::Proto::LastWorld* Arena::CreateMaybeMessage<::Proto::LastWorld>(Arena*);
template<> ::Proto::Player* Arena::CreateMaybeMessage<::Proto::Player>(Arena*);
template<> ::Proto::PlayerBase* Arena::CreateMaybeMessage<::Proto::PlayerBase>(Arena*);
template<> ::Proto::PlayerMisc* Arena::CreateMaybeMessage<::Proto::PlayerMisc>(Arena*);
template<> ::Proto::Vector3* Arena::CreateMaybeMessage<::Proto::Vector3>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Proto {

enum Gender : int {
  none = 0,
  male = 1,
  female = 2,
  Gender_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Gender_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Gender_IsValid(int value);
constexpr Gender Gender_MIN = none;
constexpr Gender Gender_MAX = female;
constexpr int Gender_ARRAYSIZE = Gender_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Gender_descriptor();
template<typename T>
inline const std::string& Gender_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Gender>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Gender_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Gender_descriptor(), enum_t_value);
}
inline bool Gender_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Gender* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Gender>(
    Gender_descriptor(), name, value);
}
// ===================================================================

class Vector3 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Vector3) */ {
 public:
  inline Vector3() : Vector3(nullptr) {}
  ~Vector3() override;
  explicit constexpr Vector3(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vector3(const Vector3& from);
  Vector3(Vector3&& from) noexcept
    : Vector3() {
    *this = ::std::move(from);
  }

  inline Vector3& operator=(const Vector3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector3& operator=(Vector3&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vector3& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vector3* internal_default_instance() {
    return reinterpret_cast<const Vector3*>(
               &_Vector3_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Vector3& a, Vector3& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector3* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vector3* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Vector3* New() const final {
    return new Vector3();
  }

  Vector3* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Vector3>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vector3& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Vector3& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Vector3";
  }
  protected:
  explicit Vector3(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:Proto.Vector3)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_db_2eproto;
};
// -------------------------------------------------------------------

class PlayerBase final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.PlayerBase) */ {
 public:
  inline PlayerBase() : PlayerBase(nullptr) {}
  ~PlayerBase() override;
  explicit constexpr PlayerBase(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerBase(const PlayerBase& from);
  PlayerBase(PlayerBase&& from) noexcept
    : PlayerBase() {
    *this = ::std::move(from);
  }

  inline PlayerBase& operator=(const PlayerBase& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerBase& operator=(PlayerBase&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerBase& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerBase* internal_default_instance() {
    return reinterpret_cast<const PlayerBase*>(
               &_PlayerBase_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PlayerBase& a, PlayerBase& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerBase* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerBase* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlayerBase* New() const final {
    return new PlayerBase();
  }

  PlayerBase* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlayerBase>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerBase& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const PlayerBase& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerBase* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.PlayerBase";
  }
  protected:
  explicit PlayerBase(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGenderFieldNumber = 1,
    kLevelFieldNumber = 2,
  };
  // .Proto.Gender gender = 1;
  void clear_gender();
  ::Proto::Gender gender() const;
  void set_gender(::Proto::Gender value);
  private:
  ::Proto::Gender _internal_gender() const;
  void _internal_set_gender(::Proto::Gender value);
  public:

  // int32 level = 2;
  void clear_level();
  ::PROTOBUF_NAMESPACE_ID::int32 level() const;
  void set_level(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_level() const;
  void _internal_set_level(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Proto.PlayerBase)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int gender_;
  ::PROTOBUF_NAMESPACE_ID::int32 level_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_db_2eproto;
};
// -------------------------------------------------------------------

class LastWorld final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.LastWorld) */ {
 public:
  inline LastWorld() : LastWorld(nullptr) {}
  ~LastWorld() override;
  explicit constexpr LastWorld(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LastWorld(const LastWorld& from);
  LastWorld(LastWorld&& from) noexcept
    : LastWorld() {
    *this = ::std::move(from);
  }

  inline LastWorld& operator=(const LastWorld& from) {
    CopyFrom(from);
    return *this;
  }
  inline LastWorld& operator=(LastWorld&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LastWorld& default_instance() {
    return *internal_default_instance();
  }
  static inline const LastWorld* internal_default_instance() {
    return reinterpret_cast<const LastWorld*>(
               &_LastWorld_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(LastWorld& a, LastWorld& b) {
    a.Swap(&b);
  }
  inline void Swap(LastWorld* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LastWorld* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LastWorld* New() const final {
    return new LastWorld();
  }

  LastWorld* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LastWorld>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LastWorld& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const LastWorld& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LastWorld* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.LastWorld";
  }
  protected:
  explicit LastWorld(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 3,
    kWorldSnFieldNumber = 2,
    kWorldIdFieldNumber = 1,
  };
  // .Proto.Vector3 position = 3;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::Proto::Vector3& position() const;
  PROTOBUF_MUST_USE_RESULT ::Proto::Vector3* release_position();
  ::Proto::Vector3* mutable_position();
  void set_allocated_position(::Proto::Vector3* position);
  private:
  const ::Proto::Vector3& _internal_position() const;
  ::Proto::Vector3* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::Proto::Vector3* position);
  ::Proto::Vector3* unsafe_arena_release_position();

  // int64 world_sn = 2;
  void clear_world_sn();
  ::PROTOBUF_NAMESPACE_ID::int64 world_sn() const;
  void set_world_sn(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_world_sn() const;
  void _internal_set_world_sn(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 world_id = 1;
  void clear_world_id();
  ::PROTOBUF_NAMESPACE_ID::int32 world_id() const;
  void set_world_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_world_id() const;
  void _internal_set_world_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Proto.LastWorld)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Proto::Vector3* position_;
  ::PROTOBUF_NAMESPACE_ID::int64 world_sn_;
  ::PROTOBUF_NAMESPACE_ID::int32 world_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_db_2eproto;
};
// -------------------------------------------------------------------

class PlayerMisc final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.PlayerMisc) */ {
 public:
  inline PlayerMisc() : PlayerMisc(nullptr) {}
  ~PlayerMisc() override;
  explicit constexpr PlayerMisc(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerMisc(const PlayerMisc& from);
  PlayerMisc(PlayerMisc&& from) noexcept
    : PlayerMisc() {
    *this = ::std::move(from);
  }

  inline PlayerMisc& operator=(const PlayerMisc& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerMisc& operator=(PlayerMisc&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerMisc& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerMisc* internal_default_instance() {
    return reinterpret_cast<const PlayerMisc*>(
               &_PlayerMisc_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PlayerMisc& a, PlayerMisc& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerMisc* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerMisc* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlayerMisc* New() const final {
    return new PlayerMisc();
  }

  PlayerMisc* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlayerMisc>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerMisc& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const PlayerMisc& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerMisc* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.PlayerMisc";
  }
  protected:
  explicit PlayerMisc(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLastWorldFieldNumber = 1,
    kLastDungeonFieldNumber = 2,
    kOnlineVersionFieldNumber = 3,
  };
  // .Proto.LastWorld last_world = 1;
  bool has_last_world() const;
  private:
  bool _internal_has_last_world() const;
  public:
  void clear_last_world();
  const ::Proto::LastWorld& last_world() const;
  PROTOBUF_MUST_USE_RESULT ::Proto::LastWorld* release_last_world();
  ::Proto::LastWorld* mutable_last_world();
  void set_allocated_last_world(::Proto::LastWorld* last_world);
  private:
  const ::Proto::LastWorld& _internal_last_world() const;
  ::Proto::LastWorld* _internal_mutable_last_world();
  public:
  void unsafe_arena_set_allocated_last_world(
      ::Proto::LastWorld* last_world);
  ::Proto::LastWorld* unsafe_arena_release_last_world();

  // .Proto.LastWorld last_dungeon = 2;
  bool has_last_dungeon() const;
  private:
  bool _internal_has_last_dungeon() const;
  public:
  void clear_last_dungeon();
  const ::Proto::LastWorld& last_dungeon() const;
  PROTOBUF_MUST_USE_RESULT ::Proto::LastWorld* release_last_dungeon();
  ::Proto::LastWorld* mutable_last_dungeon();
  void set_allocated_last_dungeon(::Proto::LastWorld* last_dungeon);
  private:
  const ::Proto::LastWorld& _internal_last_dungeon() const;
  ::Proto::LastWorld* _internal_mutable_last_dungeon();
  public:
  void unsafe_arena_set_allocated_last_dungeon(
      ::Proto::LastWorld* last_dungeon);
  ::Proto::LastWorld* unsafe_arena_release_last_dungeon();

  // int32 online_version = 3;
  void clear_online_version();
  ::PROTOBUF_NAMESPACE_ID::int32 online_version() const;
  void set_online_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_online_version() const;
  void _internal_set_online_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Proto.PlayerMisc)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Proto::LastWorld* last_world_;
  ::Proto::LastWorld* last_dungeon_;
  ::PROTOBUF_NAMESPACE_ID::int32 online_version_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_db_2eproto;
};
// -------------------------------------------------------------------

class Player final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Player) */ {
 public:
  inline Player() : Player(nullptr) {}
  ~Player() override;
  explicit constexpr Player(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Player(const Player& from);
  Player(Player&& from) noexcept
    : Player() {
    *this = ::std::move(from);
  }

  inline Player& operator=(const Player& from) {
    CopyFrom(from);
    return *this;
  }
  inline Player& operator=(Player&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Player& default_instance() {
    return *internal_default_instance();
  }
  static inline const Player* internal_default_instance() {
    return reinterpret_cast<const Player*>(
               &_Player_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Player& a, Player& b) {
    a.Swap(&b);
  }
  inline void Swap(Player* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Player* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Player* New() const final {
    return new Player();
  }

  Player* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Player>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Player& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Player& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Player* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Player";
  }
  protected:
  explicit Player(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kBaseFieldNumber = 3,
    kMiscFieldNumber = 4,
    kSnFieldNumber = 1,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .Proto.PlayerBase base = 3;
  bool has_base() const;
  private:
  bool _internal_has_base() const;
  public:
  void clear_base();
  const ::Proto::PlayerBase& base() const;
  PROTOBUF_MUST_USE_RESULT ::Proto::PlayerBase* release_base();
  ::Proto::PlayerBase* mutable_base();
  void set_allocated_base(::Proto::PlayerBase* base);
  private:
  const ::Proto::PlayerBase& _internal_base() const;
  ::Proto::PlayerBase* _internal_mutable_base();
  public:
  void unsafe_arena_set_allocated_base(
      ::Proto::PlayerBase* base);
  ::Proto::PlayerBase* unsafe_arena_release_base();

  // .Proto.PlayerMisc misc = 4;
  bool has_misc() const;
  private:
  bool _internal_has_misc() const;
  public:
  void clear_misc();
  const ::Proto::PlayerMisc& misc() const;
  PROTOBUF_MUST_USE_RESULT ::Proto::PlayerMisc* release_misc();
  ::Proto::PlayerMisc* mutable_misc();
  void set_allocated_misc(::Proto::PlayerMisc* misc);
  private:
  const ::Proto::PlayerMisc& _internal_misc() const;
  ::Proto::PlayerMisc* _internal_mutable_misc();
  public:
  void unsafe_arena_set_allocated_misc(
      ::Proto::PlayerMisc* misc);
  ::Proto::PlayerMisc* unsafe_arena_release_misc();

  // uint64 sn = 1;
  void clear_sn();
  ::PROTOBUF_NAMESPACE_ID::uint64 sn() const;
  void set_sn(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_sn() const;
  void _internal_set_sn(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:Proto.Player)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::Proto::PlayerBase* base_;
  ::Proto::PlayerMisc* misc_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sn_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_db_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vector3

// float x = 1;
inline void Vector3::clear_x() {
  x_ = 0;
}
inline float Vector3::_internal_x() const {
  return x_;
}
inline float Vector3::x() const {
  // @@protoc_insertion_point(field_get:Proto.Vector3.x)
  return _internal_x();
}
inline void Vector3::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Vector3::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Proto.Vector3.x)
}

// float y = 2;
inline void Vector3::clear_y() {
  y_ = 0;
}
inline float Vector3::_internal_y() const {
  return y_;
}
inline float Vector3::y() const {
  // @@protoc_insertion_point(field_get:Proto.Vector3.y)
  return _internal_y();
}
inline void Vector3::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Vector3::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Proto.Vector3.y)
}

// float z = 3;
inline void Vector3::clear_z() {
  z_ = 0;
}
inline float Vector3::_internal_z() const {
  return z_;
}
inline float Vector3::z() const {
  // @@protoc_insertion_point(field_get:Proto.Vector3.z)
  return _internal_z();
}
inline void Vector3::_internal_set_z(float value) {
  
  z_ = value;
}
inline void Vector3::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Proto.Vector3.z)
}

// -------------------------------------------------------------------

// PlayerBase

// .Proto.Gender gender = 1;
inline void PlayerBase::clear_gender() {
  gender_ = 0;
}
inline ::Proto::Gender PlayerBase::_internal_gender() const {
  return static_cast< ::Proto::Gender >(gender_);
}
inline ::Proto::Gender PlayerBase::gender() const {
  // @@protoc_insertion_point(field_get:Proto.PlayerBase.gender)
  return _internal_gender();
}
inline void PlayerBase::_internal_set_gender(::Proto::Gender value) {
  
  gender_ = value;
}
inline void PlayerBase::set_gender(::Proto::Gender value) {
  _internal_set_gender(value);
  // @@protoc_insertion_point(field_set:Proto.PlayerBase.gender)
}

// int32 level = 2;
inline void PlayerBase::clear_level() {
  level_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PlayerBase::_internal_level() const {
  return level_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PlayerBase::level() const {
  // @@protoc_insertion_point(field_get:Proto.PlayerBase.level)
  return _internal_level();
}
inline void PlayerBase::_internal_set_level(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  level_ = value;
}
inline void PlayerBase::set_level(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:Proto.PlayerBase.level)
}

// -------------------------------------------------------------------

// LastWorld

// int32 world_id = 1;
inline void LastWorld::clear_world_id() {
  world_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LastWorld::_internal_world_id() const {
  return world_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LastWorld::world_id() const {
  // @@protoc_insertion_point(field_get:Proto.LastWorld.world_id)
  return _internal_world_id();
}
inline void LastWorld::_internal_set_world_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  world_id_ = value;
}
inline void LastWorld::set_world_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_world_id(value);
  // @@protoc_insertion_point(field_set:Proto.LastWorld.world_id)
}

// int64 world_sn = 2;
inline void LastWorld::clear_world_sn() {
  world_sn_ = int64_t{0};
}
inline ::PROTOBUF_NAMESPACE_ID::int64 LastWorld::_internal_world_sn() const {
  return world_sn_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 LastWorld::world_sn() const {
  // @@protoc_insertion_point(field_get:Proto.LastWorld.world_sn)
  return _internal_world_sn();
}
inline void LastWorld::_internal_set_world_sn(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  world_sn_ = value;
}
inline void LastWorld::set_world_sn(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_world_sn(value);
  // @@protoc_insertion_point(field_set:Proto.LastWorld.world_sn)
}

// .Proto.Vector3 position = 3;
inline bool LastWorld::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool LastWorld::has_position() const {
  return _internal_has_position();
}
inline void LastWorld::clear_position() {
  if (GetArenaForAllocation() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
}
inline const ::Proto::Vector3& LastWorld::_internal_position() const {
  const ::Proto::Vector3* p = position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::Vector3&>(
      ::Proto::_Vector3_default_instance_);
}
inline const ::Proto::Vector3& LastWorld::position() const {
  // @@protoc_insertion_point(field_get:Proto.LastWorld.position)
  return _internal_position();
}
inline void LastWorld::unsafe_arena_set_allocated_position(
    ::Proto::Vector3* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.LastWorld.position)
}
inline ::Proto::Vector3* LastWorld::release_position() {
  
  ::Proto::Vector3* temp = position_;
  position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Proto::Vector3* LastWorld::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:Proto.LastWorld.position)
  
  ::Proto::Vector3* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::Proto::Vector3* LastWorld::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::Vector3>(GetArenaForAllocation());
    position_ = p;
  }
  return position_;
}
inline ::Proto::Vector3* LastWorld::mutable_position() {
  ::Proto::Vector3* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:Proto.LastWorld.position)
  return _msg;
}
inline void LastWorld::set_allocated_position(::Proto::Vector3* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Proto::Vector3>::GetOwningArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:Proto.LastWorld.position)
}

// -------------------------------------------------------------------

// PlayerMisc

// .Proto.LastWorld last_world = 1;
inline bool PlayerMisc::_internal_has_last_world() const {
  return this != internal_default_instance() && last_world_ != nullptr;
}
inline bool PlayerMisc::has_last_world() const {
  return _internal_has_last_world();
}
inline void PlayerMisc::clear_last_world() {
  if (GetArenaForAllocation() == nullptr && last_world_ != nullptr) {
    delete last_world_;
  }
  last_world_ = nullptr;
}
inline const ::Proto::LastWorld& PlayerMisc::_internal_last_world() const {
  const ::Proto::LastWorld* p = last_world_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::LastWorld&>(
      ::Proto::_LastWorld_default_instance_);
}
inline const ::Proto::LastWorld& PlayerMisc::last_world() const {
  // @@protoc_insertion_point(field_get:Proto.PlayerMisc.last_world)
  return _internal_last_world();
}
inline void PlayerMisc::unsafe_arena_set_allocated_last_world(
    ::Proto::LastWorld* last_world) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(last_world_);
  }
  last_world_ = last_world;
  if (last_world) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.PlayerMisc.last_world)
}
inline ::Proto::LastWorld* PlayerMisc::release_last_world() {
  
  ::Proto::LastWorld* temp = last_world_;
  last_world_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Proto::LastWorld* PlayerMisc::unsafe_arena_release_last_world() {
  // @@protoc_insertion_point(field_release:Proto.PlayerMisc.last_world)
  
  ::Proto::LastWorld* temp = last_world_;
  last_world_ = nullptr;
  return temp;
}
inline ::Proto::LastWorld* PlayerMisc::_internal_mutable_last_world() {
  
  if (last_world_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::LastWorld>(GetArenaForAllocation());
    last_world_ = p;
  }
  return last_world_;
}
inline ::Proto::LastWorld* PlayerMisc::mutable_last_world() {
  ::Proto::LastWorld* _msg = _internal_mutable_last_world();
  // @@protoc_insertion_point(field_mutable:Proto.PlayerMisc.last_world)
  return _msg;
}
inline void PlayerMisc::set_allocated_last_world(::Proto::LastWorld* last_world) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete last_world_;
  }
  if (last_world) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Proto::LastWorld>::GetOwningArena(last_world);
    if (message_arena != submessage_arena) {
      last_world = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, last_world, submessage_arena);
    }
    
  } else {
    
  }
  last_world_ = last_world;
  // @@protoc_insertion_point(field_set_allocated:Proto.PlayerMisc.last_world)
}

// .Proto.LastWorld last_dungeon = 2;
inline bool PlayerMisc::_internal_has_last_dungeon() const {
  return this != internal_default_instance() && last_dungeon_ != nullptr;
}
inline bool PlayerMisc::has_last_dungeon() const {
  return _internal_has_last_dungeon();
}
inline void PlayerMisc::clear_last_dungeon() {
  if (GetArenaForAllocation() == nullptr && last_dungeon_ != nullptr) {
    delete last_dungeon_;
  }
  last_dungeon_ = nullptr;
}
inline const ::Proto::LastWorld& PlayerMisc::_internal_last_dungeon() const {
  const ::Proto::LastWorld* p = last_dungeon_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::LastWorld&>(
      ::Proto::_LastWorld_default_instance_);
}
inline const ::Proto::LastWorld& PlayerMisc::last_dungeon() const {
  // @@protoc_insertion_point(field_get:Proto.PlayerMisc.last_dungeon)
  return _internal_last_dungeon();
}
inline void PlayerMisc::unsafe_arena_set_allocated_last_dungeon(
    ::Proto::LastWorld* last_dungeon) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(last_dungeon_);
  }
  last_dungeon_ = last_dungeon;
  if (last_dungeon) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.PlayerMisc.last_dungeon)
}
inline ::Proto::LastWorld* PlayerMisc::release_last_dungeon() {
  
  ::Proto::LastWorld* temp = last_dungeon_;
  last_dungeon_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Proto::LastWorld* PlayerMisc::unsafe_arena_release_last_dungeon() {
  // @@protoc_insertion_point(field_release:Proto.PlayerMisc.last_dungeon)
  
  ::Proto::LastWorld* temp = last_dungeon_;
  last_dungeon_ = nullptr;
  return temp;
}
inline ::Proto::LastWorld* PlayerMisc::_internal_mutable_last_dungeon() {
  
  if (last_dungeon_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::LastWorld>(GetArenaForAllocation());
    last_dungeon_ = p;
  }
  return last_dungeon_;
}
inline ::Proto::LastWorld* PlayerMisc::mutable_last_dungeon() {
  ::Proto::LastWorld* _msg = _internal_mutable_last_dungeon();
  // @@protoc_insertion_point(field_mutable:Proto.PlayerMisc.last_dungeon)
  return _msg;
}
inline void PlayerMisc::set_allocated_last_dungeon(::Proto::LastWorld* last_dungeon) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete last_dungeon_;
  }
  if (last_dungeon) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Proto::LastWorld>::GetOwningArena(last_dungeon);
    if (message_arena != submessage_arena) {
      last_dungeon = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, last_dungeon, submessage_arena);
    }
    
  } else {
    
  }
  last_dungeon_ = last_dungeon;
  // @@protoc_insertion_point(field_set_allocated:Proto.PlayerMisc.last_dungeon)
}

// int32 online_version = 3;
inline void PlayerMisc::clear_online_version() {
  online_version_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PlayerMisc::_internal_online_version() const {
  return online_version_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PlayerMisc::online_version() const {
  // @@protoc_insertion_point(field_get:Proto.PlayerMisc.online_version)
  return _internal_online_version();
}
inline void PlayerMisc::_internal_set_online_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  online_version_ = value;
}
inline void PlayerMisc::set_online_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_online_version(value);
  // @@protoc_insertion_point(field_set:Proto.PlayerMisc.online_version)
}

// -------------------------------------------------------------------

// Player

// uint64 sn = 1;
inline void Player::clear_sn() {
  sn_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Player::_internal_sn() const {
  return sn_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Player::sn() const {
  // @@protoc_insertion_point(field_get:Proto.Player.sn)
  return _internal_sn();
}
inline void Player::_internal_set_sn(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  sn_ = value;
}
inline void Player::set_sn(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_sn(value);
  // @@protoc_insertion_point(field_set:Proto.Player.sn)
}

// string name = 2;
inline void Player::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& Player::name() const {
  // @@protoc_insertion_point(field_get:Proto.Player.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Player::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Proto.Player.name)
}
inline std::string* Player::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Proto.Player.name)
  return _s;
}
inline const std::string& Player::_internal_name() const {
  return name_.Get();
}
inline void Player::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Player::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Player::release_name() {
  // @@protoc_insertion_point(field_release:Proto.Player.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Player::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Proto.Player.name)
}

// .Proto.PlayerBase base = 3;
inline bool Player::_internal_has_base() const {
  return this != internal_default_instance() && base_ != nullptr;
}
inline bool Player::has_base() const {
  return _internal_has_base();
}
inline void Player::clear_base() {
  if (GetArenaForAllocation() == nullptr && base_ != nullptr) {
    delete base_;
  }
  base_ = nullptr;
}
inline const ::Proto::PlayerBase& Player::_internal_base() const {
  const ::Proto::PlayerBase* p = base_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::PlayerBase&>(
      ::Proto::_PlayerBase_default_instance_);
}
inline const ::Proto::PlayerBase& Player::base() const {
  // @@protoc_insertion_point(field_get:Proto.Player.base)
  return _internal_base();
}
inline void Player::unsafe_arena_set_allocated_base(
    ::Proto::PlayerBase* base) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(base_);
  }
  base_ = base;
  if (base) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.Player.base)
}
inline ::Proto::PlayerBase* Player::release_base() {
  
  ::Proto::PlayerBase* temp = base_;
  base_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Proto::PlayerBase* Player::unsafe_arena_release_base() {
  // @@protoc_insertion_point(field_release:Proto.Player.base)
  
  ::Proto::PlayerBase* temp = base_;
  base_ = nullptr;
  return temp;
}
inline ::Proto::PlayerBase* Player::_internal_mutable_base() {
  
  if (base_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::PlayerBase>(GetArenaForAllocation());
    base_ = p;
  }
  return base_;
}
inline ::Proto::PlayerBase* Player::mutable_base() {
  ::Proto::PlayerBase* _msg = _internal_mutable_base();
  // @@protoc_insertion_point(field_mutable:Proto.Player.base)
  return _msg;
}
inline void Player::set_allocated_base(::Proto::PlayerBase* base) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete base_;
  }
  if (base) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Proto::PlayerBase>::GetOwningArena(base);
    if (message_arena != submessage_arena) {
      base = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, base, submessage_arena);
    }
    
  } else {
    
  }
  base_ = base;
  // @@protoc_insertion_point(field_set_allocated:Proto.Player.base)
}

// .Proto.PlayerMisc misc = 4;
inline bool Player::_internal_has_misc() const {
  return this != internal_default_instance() && misc_ != nullptr;
}
inline bool Player::has_misc() const {
  return _internal_has_misc();
}
inline void Player::clear_misc() {
  if (GetArenaForAllocation() == nullptr && misc_ != nullptr) {
    delete misc_;
  }
  misc_ = nullptr;
}
inline const ::Proto::PlayerMisc& Player::_internal_misc() const {
  const ::Proto::PlayerMisc* p = misc_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::PlayerMisc&>(
      ::Proto::_PlayerMisc_default_instance_);
}
inline const ::Proto::PlayerMisc& Player::misc() const {
  // @@protoc_insertion_point(field_get:Proto.Player.misc)
  return _internal_misc();
}
inline void Player::unsafe_arena_set_allocated_misc(
    ::Proto::PlayerMisc* misc) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(misc_);
  }
  misc_ = misc;
  if (misc) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.Player.misc)
}
inline ::Proto::PlayerMisc* Player::release_misc() {
  
  ::Proto::PlayerMisc* temp = misc_;
  misc_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Proto::PlayerMisc* Player::unsafe_arena_release_misc() {
  // @@protoc_insertion_point(field_release:Proto.Player.misc)
  
  ::Proto::PlayerMisc* temp = misc_;
  misc_ = nullptr;
  return temp;
}
inline ::Proto::PlayerMisc* Player::_internal_mutable_misc() {
  
  if (misc_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::PlayerMisc>(GetArenaForAllocation());
    misc_ = p;
  }
  return misc_;
}
inline ::Proto::PlayerMisc* Player::mutable_misc() {
  ::Proto::PlayerMisc* _msg = _internal_mutable_misc();
  // @@protoc_insertion_point(field_mutable:Proto.Player.misc)
  return _msg;
}
inline void Player::set_allocated_misc(::Proto::PlayerMisc* misc) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete misc_;
  }
  if (misc) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Proto::PlayerMisc>::GetOwningArena(misc);
    if (message_arena != submessage_arena) {
      misc = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, misc, submessage_arena);
    }
    
  } else {
    
  }
  misc_ = misc;
  // @@protoc_insertion_point(field_set_allocated:Proto.Player.misc)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Proto::Gender> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Proto::Gender>() {
  return ::Proto::Gender_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_db_2eproto
